name: Testing with Pytest
run-name: Pytest

on:
  push:
    branches:
      - main
      - 'releases/**'
    paths: 
      - 'LAB3/**'   # Only trigger if any file inside LAB3/ changes

  label:
    types:
      - created
  issues:
    types:
      - opened
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./LAB3/
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.18'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests and generate XML report
      run: pytest --junitxml=pytest-report.xml
      continue-on-error: false

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: LAB3/pytest-report.xml

    - name: Notify on success
      if: success()
      run: echo "Tests passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Tests failed"